services:
  django:
    image: python:3.8.10
    container_name: 
    environment:
      - IP=
      - SECRET_KEY=
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - YANDEX_ID=
      - YANDEX_SECRET=
      - GITHUB_ID=
      - GITHUB_SECRET=
      - ADMIN_NAME=
      - ADMIN_EMAIL=
      - TELEGRAM_BOT_TOKEN=
      - REDIS_LOCATION=
    volumes:
      - site:/noted
      - static:/noted/frontend
      - media:/noted/media
    expose:
      - 8000
    entrypoint: ./entrypoint.sh
    networks:
      network:
        ipv4_address: 172.18.1.3

  gateway:
    image: nginx
    container_name: 
    volumes:
      - static:/noted/frontend
      - media:/noted/media
      - /app/nginx-settings/noted-gateway:/etc/nginx
    expose:
      - 80
    networks:
      network:
        ipv4_address: 172.18.1.2
    depends_on:
      - django

volumes:
  site:
  static:
  media:

networks:
  network:
    name: infra_network
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24
